CREATE DATABASE tabcorp
    WITH 
    OWNER = demo
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1 IF NOT EXISTS `tabcorp`;
    
-- User: demo
-- DROP USER demo;

CREATE USER demo WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION;